[package]
name = "stockholm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
dirs = { version = "*"}
walkdir = {version = "*"}
rand = {version = "*"}
chacha20poly1305 = { version = "0.10.0", features = [] }
hex = "*"
